imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        cacic_version: 3.0.0
    form:
        resources:
            - "BcBootstrapBundle:Form:form_div_layout.html.twig"

bc_bootstrap:
    assets_dir:  "%kernel.root_dir%/../vendor/twitter/bootstrap"
    jquery_path: "%kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js"
    less_filter: lessphp

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ CacicCommonBundle, CacicRelatorioBundle ]
    java: /usr/bin/java
    filters:
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed-0.4.5.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.2.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.2.jar"
        lessphp:
            file: "%kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php"
            apply_to: "\.less$"
        cssrewrite: ~
    assets:
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/less/responsive.less"
            filters:
                - lessphp
                - cssrewrite
            output: css/bootstrap.css
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-transition.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-alert.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-button.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-carousel.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-collapse.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-dropdown.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-modal.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tooltip.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-popover.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-scrollspy.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tab.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-typeahead.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-affix.js"
            output: js/bootstrap.js
        jquery_js:
            inputs:
                - "%kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js"
            output: js/jquery.js
            filters: [?yui_js]
        bootstrap_less:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less'
            filters: [lessphp,cssembed]


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# KNP Paginator Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension