CocarBundle_cocar_annotation:
            resource: "@CocarBundle/Resources/config/routing.yml"
            prefix:   /cocar/
cacic_ws:
    resource: "@CacicWSBundle/Resources/config/routing.yml"
    prefix:   /ws/

cacic_relatorio:
    resource: "@CacicRelatorioBundle/Resources/config/routing.yml"
    prefix:   /relatorio/

cacic_common:
    resource: "@CacicCommonBundle/Resources/config/routing.yml"
    prefix:   /

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

CocarBundle_cocar_annotation:
            resource: "@CocarBundle/Resources/config/routing.yml"
            prefix:   /cocar

lexik_monolog_browser:
    resource: "@LexikMonologBrowserBundle/Resources/config/routing.xml"
    prefix:   /admin/monolog

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
