Cacic\CommonBundle\Entity\ComputadorColetaHistorico:
    type: entity
    table: computador_coleta_historico
    fields:
        idComputadorColetaHistorico:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_computador_coleta_historico
            generator:
                strategy: IDENTITY
        teClassPropertyValue:
            type: text
            nullable: false
            column: te_class_property_value
        dtHrInclusao:
            type: datetime
            nullable: false
            column: dt_hr_inclusao
            columnDefinition: DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        computadorColeta:
            targetEntity: ComputadorColeta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_computador_coleta:
                    referencedColumnName: id_computador_coleta
            orphanRemoval: false
        computador:
            targetEntity: Computador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_computador:
                    referencedColumnName: id_computador
            orphanRemoval: false
        classProperty:
            targetEntity: ClassProperty
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_class_property:
                    referencedColumnName: id_class_property
            orphanRemoval: false
    lifecycleCallbacks: {  }