Cacic\CommonBundle\Entity\GrupoUsuario:
    type: entity
    table: grupo_usuario
    repositoryClass: Cacic\CommonBundle\Entity\GrupoUsuarioRepository
    fields:
        idGrupoUsuario:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_grupo_usuario
            generator:
                strategy: IDENTITY
        nmGrupoUsuarios:
            type: text
            fixed: false
            nullable: false
            column: nm_grupo_usuarios
        teGrupoUsuarios:
            type: text
            fixed: false
            nullable: true
            column: te_grupo_usuarios
        teMenuGrupo:
            type: text
            fixed: false
            nullable: true
            column: te_menu_grupo
        teDescricaoGrupo:
            type: text
            nullable: true
            column: te_descricao_grupo
        csNivelAdministracao:
            type: integer
            nullable: true
            column: cs_nivel_administracao
    lifecycleCallbacks: {  }
