Cacic\CommonBundle\Entity\RedeGrupoFtp:
    type: entity
    table: rede_grupo_ftp
    fields:
        idFtp:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_ftp
            generator:
                strategy: IDENTITY
        nuHoraInicio:
            type: time
            nullable: false
            column: nu_hora_inicio
        nuHoraFim:
            type: time
            nullable: false
            column: nu_hora_fim
    manyToOne:
        idRede:
            targetEntity: Rede
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rede:
                    referencedColumnName: id_rede
            orphanRemoval: false
        idComputador:
            targetEntity: Computador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_computador:
                    referencedColumnName: id_computador
            orphanRemoval: false
    lifecycleCallbacks: {  }
